base :
  project: simple_app-winequaltiy
  random_state: 42
  target_col: TARGET

data_soucre:
  s3_source: data_given/winequality.csv

load_data:
  raw_data_csv: data/raw/winequality.csv

split_data:
  train_path : data/processed/train_winequality.csv
  test_path : data/processed/test_winequaltiy.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params: 
      alpha: 0.88
      l1_ration: 0.2

model_dir: saved_models


